### ISSUE TITLE
Crash when opening album list

### ISSUE THREAD

**Issue by christantoan** [jruesga/PhotoPhase#32]
After the app has finished scanning my device for albums, it crashed (possibly due to large number of images in one folder) 

Stack trace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.ruesga.android.wallpapers.photophase.e.a.a(SourceFile:216)
	at com.ruesga.android.wallpapers.photophase.e.a.b(SourceFile:157)
	at com.ruesga.android.wallpapers.photophase.d.a.a(SourceFile:122)
	at com.ruesga.android.wallpapers.photophase.d.a.doInBackground(SourceFile:34)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more

**Comment by jruesga** [comment]
https://github.com/jruesga/PhotoPhase/commit/183cd41fc316396cc30b86e873f2db7b4d168adc
